namespace Win32.Enums;

public enum WindowCompositionAttribute
{
    WCA_ACCENT_POLICY = 19,
    WCA_EXCLUDED_FROM_DDA = 24
}

public enum AccentState
{
    ACCENT_DISABLED = 0,
    ACCENT_ENABLE_GRADIENT = 1,
    ACCENT_ENABLE_TRANSPARENTGRADIENT = 2,
    ACCENT_ENABLE_BLURBEHIND = 3,
    ACCENT_ENABLE_ACRYLICBLURBEHIND = 4,
    ACCENT_INVALID_STATE = 5,
}
